name: RealPAPI
version: '${project.version}'
main: ru.meinych15.realpapi.RealPAPI
api-version: '1.16'
depend: [PlaceholderAPI]
commands:
  rpapi:
    description: RealPAPI commands
    usage: /rpapi reload
    permission: rpapi.reload